### ISSUE TITLE
failure in Action: Update docker-compose.yml with new image tag

### ISSUE THREAD

**Issue by sgdkd** [UBC-MDS/group-2#44]
![image](https://github.com/user-attachments/assets/6e6633af-1d67-4a61-be2a-2412fb514a25)
@Psingh238 Could you pls double check?  #33 Thanks.

**Comment by Psingh238** [comment]
Hi, sorry for not noticing this earlier but this looks expected since this happened on the creation of the release tag which git cannot do since a tag is not a branch and you cannot push to a tag. `docker-compose.yml` still has the correct image tag so this seems to just be what happens when creating the tag. I think the workflow has no issue since it worked correctly and automatically when it was merged onto the main branch.

**Comment by musiccabin** [comment]
@sgdkd if you're okay with the answer you got, you can close this issue :) ty
